[package]
name = "email_server"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
email_connect = { path = "./email_connect" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

